import Foundation

/// Serializes recurring-transaction generation so the app-launch run and the
/// background-task run can never overlap (DATAINTEGRITY-4).
///
/// Both entry points call `generate()`. The actor keeps a single in-flight
/// `Task`: a second caller arriving while a run is active awaits that same run
/// instead of starting its own, collapsing concurrent triggers into one
/// execution. Combined with the use case's per-occurrence idempotency, this
/// guarantees an occurrence is never generated twice — whether two triggers
/// overlap (coalesced here) or run back-to-back (skipped by the day key).
///
/// This is intentionally lock-based rather than schema-based (no unique
/// constraint), keeping A8 independent of the SwiftData schema version.
actor RecurringGenerationCoordinator {
    private let useCase: GenerateRecurringTransactionsUseCase
    private var inFlight: Task<Int, Error>?

    init(useCase: GenerateRecurringTransactionsUseCase) {
        self.useCase = useCase
    }

    /// Run generation, coalescing with any run already in progress.
    /// - Returns: the number of transactions generated by the (shared) run.
    @discardableResult
    func generate() async throws -> Int {
        if let inFlight {
            return try await inFlight.value
        }

        let task = Task { try await useCase.execute() }
        inFlight = task
        defer { inFlight = nil }
        return try await task.value
    }
}
