import SwiftUI
import Charts
import VittoraCore

// MARK: - Monthly / annual multi-page PDF (R1)

enum MonthlyReportPDFDocument {
    /// Builds A4 pages: summary + chart on page 1, monthly table paginated across following pages.
    @MainActor
    static func pages(
        reportTitle: String,
        period: String,
        monthlyData: [MonthlyData],
        currencyCode: String,
        totalIncome: Decimal,
        totalExpense: Decimal,
        netSavings: Decimal
    ) -> [ReportPDFPage] {
        let rows = Array(monthlyData.reversed())
        let tableChunks = chunkRows(rows, rowsPerPage: rowsPerContinuationPage)
        let totalPages = 1 + tableChunks.count

        var pages: [ReportPDFPage] = [
            ReportPDFPage(
                reportTitle: reportTitle,
                period: period,
                pageNumber: 1,
                pageCount: max(totalPages, 1),
                content: .summaryAndChart(
                    SummaryChartContent(
                        currencyCode: currencyCode,
                        totalIncome: totalIncome,
                        totalExpense: totalExpense,
                        netSavings: netSavings,
                        monthlyData: monthlyData
                    )
                )
            )
        ]

        for (index, chunk) in tableChunks.enumerated() {
            pages.append(
                ReportPDFPage(
                    reportTitle: reportTitle,
                    period: period,
                    pageNumber: index + 2,
                    pageCount: totalPages,
                    content: .table(
                        TableContent(
                            currencyCode: currencyCode,
                            rows: chunk,
                            showsSectionTitle: index == 0
                        )
                    )
                )
            )
        }

        return pages
    }

    /// Rows that fit on a continuation page after chrome (header/footer).
    private static let rowsPerContinuationPage = 18

    private static func chunkRows(_ rows: [MonthlyData], rowsPerPage: Int) -> [[MonthlyData]] {
        guard rowsPerPage > 0, !rows.isEmpty else { return [] }
        var chunks: [[MonthlyData]] = []
        var index = 0
        while index < rows.count {
            let end = min(index + rowsPerPage, rows.count)
            chunks.append(Array(rows[index..<end]))
            index = end
        }
        return chunks
    }
}

// MARK: - Page model

struct ReportPDFPage: View {
    enum Content {
        case summaryAndChart(SummaryChartContent)
        case table(TableContent)
    }

    let reportTitle: String
    let period: String
    let pageNumber: Int
    let pageCount: Int
    let content: Content

    private var inset: CGFloat { ReportPDFRenderer.pageInset }

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            header
            contentView
                .padding(.top, 16)
            Spacer(minLength: 0)
            footer
        }
        .padding(inset)
        .frame(
            width: ReportPDFRenderer.pageWidth,
            height: ReportPDFRenderer.pageHeight,
            alignment: .topLeading
        )
        .background(Color.white)
        .foregroundStyle(Color.black)
    }

    private var header: some View {
        VStack(alignment: .leading, spacing: 4) {
            Text(String(localized: "Vittora"))
                .font(.caption.weight(.semibold))
                .foregroundStyle(Color.gray)
            Text(reportTitle)
                .font(.title2.bold())
            Text(period)
                .font(.subheadline)
                .foregroundStyle(Color.gray)
            Divider()
                .padding(.top, 8)
        }
    }

    @ViewBuilder
    private var contentView: some View {
        switch content {
        case .summaryAndChart(let summary):
            summary
        case .table(let table):
            table
        }
    }

    private var footer: some View {
        VStack(spacing: 6) {
            Divider()
            HStack(alignment: .firstTextBaseline) {
                Text(String(localized: "Generated by Vittora — data stays on your device"))
                    .font(.caption2)
                    .foregroundStyle(Color.gray)
                    .frame(maxWidth: .infinity, alignment: .leading)
                Text(
                    String(
                        localized: "Page \(pageNumber) of \(pageCount)"
                    )
                )
                .font(.caption2)
                .foregroundStyle(Color.gray)
            }
        }
        .padding(.top, 8)
    }
}

struct SummaryChartContent: View {
    let currencyCode: String
    let totalIncome: Decimal
    let totalExpense: Decimal
    let netSavings: Decimal
    let monthlyData: [MonthlyData]

    private let incomeTint = Color(red: 0.1, green: 0.55, blue: 0.25)
    private let expenseTint = Color(red: 0.85, green: 0.2, blue: 0.2)

    var body: some View {
        VStack(alignment: .leading, spacing: 20) {
            HStack(spacing: 12) {
                summaryCell(
                    title: String(localized: "Income"),
                    amount: totalIncome,
                    tint: incomeTint
                )
                summaryCell(
                    title: String(localized: "Expenses"),
                    amount: totalExpense,
                    tint: expenseTint
                )
                summaryCell(
                    title: String(localized: "Net"),
                    amount: netSavings,
                    tint: netSavings >= 0 ? incomeTint : expenseTint
                )
            }

            VStack(alignment: .leading, spacing: 10) {
                Text(String(localized: "Income vs Expenses"))
                    .font(.headline)

                Chart {
                    ForEach(monthlyData) { item in
                        BarMark(
                            x: .value(String(localized: "Month"), item.month, unit: .month),
                            y: .value(String(localized: "Income"), item.income),
                            width: .ratio(0.4)
                        )
                        .foregroundStyle(incomeTint)
                        .position(by: .value(String(localized: "Type"), String(localized: "Income")))

                        BarMark(
                            x: .value(String(localized: "Month"), item.month, unit: .month),
                            y: .value(String(localized: "Expense"), item.expense),
                            width: .ratio(0.4)
                        )
                        .foregroundStyle(expenseTint)
                        .position(by: .value(String(localized: "Type"), String(localized: "Expense")))
                    }
                }
                .chartXAxis {
                    AxisMarks(values: .stride(by: .month)) { _ in
                        AxisValueLabel(format: .dateTime.month(.abbreviated))
                            .font(.caption2)
                    }
                }
                .chartYAxis {
                    AxisMarks { _ in
                        AxisGridLine()
                        AxisValueLabel()
                            .font(.caption2)
                    }
                }
                .chartLegend(position: .top, alignment: .trailing) {
                    HStack(spacing: 12) {
                        legendItem(color: incomeTint, label: String(localized: "Income"))
                        legendItem(color: expenseTint, label: String(localized: "Expense"))
                    }
                }
                .frame(height: 240)
            }
        }
    }

    private func summaryCell(title: String, amount: Decimal, tint: Color) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            Text(title)
                .font(.caption)
                .foregroundStyle(Color.gray)
            Text(CurrencyFormatter.format(amount, currencyCode: currencyCode))
                .font(.headline)
                .foregroundStyle(tint)
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding(12)
        .background(Color(white: 0.96))
        .clipShape(RoundedRectangle(cornerRadius: 8))
    }

    private func legendItem(color: Color, label: String) -> some View {
        HStack(spacing: 4) {
            RoundedRectangle(cornerRadius: 2)
                .fill(color)
                .frame(width: 10, height: 8)
            Text(label)
                .font(.caption2)
                .foregroundStyle(Color.gray)
        }
    }
}

struct TableContent: View {
    let currencyCode: String
    let rows: [MonthlyData]
    let showsSectionTitle: Bool

    var body: some View {
        VStack(alignment: .leading, spacing: 10) {
            if showsSectionTitle {
                Text(String(localized: "Monthly Breakdown"))
                    .font(.headline)
            }

            HStack {
                Text(String(localized: "Month"))
                    .frame(maxWidth: .infinity, alignment: .leading)
                Text(String(localized: "Income"))
                    .frame(width: 88, alignment: .trailing)
                Text(String(localized: "Expense"))
                    .frame(width: 88, alignment: .trailing)
                Text(String(localized: "Net"))
                    .frame(width: 88, alignment: .trailing)
            }
            .font(.caption.bold())
            .foregroundStyle(Color.gray)

            ForEach(rows) { item in
                HStack {
                    Text(item.month.formatted(.dateTime.year().month(.wide)))
                        .frame(maxWidth: .infinity, alignment: .leading)
                    Text(CurrencyFormatter.format(item.income, currencyCode: currencyCode))
                        .frame(width: 88, alignment: .trailing)
                    Text(CurrencyFormatter.format(item.expense, currencyCode: currencyCode))
                        .frame(width: 88, alignment: .trailing)
                    Text(CurrencyFormatter.format(item.net, currencyCode: currencyCode))
                        .frame(width: 88, alignment: .trailing)
                }
                .font(.caption)
                .padding(.vertical, 4)

                Divider()
            }
        }
    }
}

// MARK: - Custom report (single-view via ReportPDFExporter)

struct CustomReportExportDocument: View {
    let result: CustomReportResult
    let currencyCode: String

    var body: some View {
        VStack(alignment: .leading, spacing: 20) {
            VStack(alignment: .leading, spacing: 6) {
                Text("Vittora")
                    .font(.caption)
                    .foregroundStyle(Color.gray)
                Text(String(localized: "Custom Report"))
                    .font(.title2.bold())
                Text(subtitle)
                    .font(.subheadline)
                    .foregroundStyle(Color.gray)
            }

            HStack {
                Text(String(localized: "Total"))
                    .font(.headline)
                Spacer()
                Text(CurrencyFormatter.format(result.total, currencyCode: currencyCode))
                    .font(.headline)
            }
            .padding(12)
            .background(Color(white: 0.96))
            .clipShape(RoundedRectangle(cornerRadius: 8))

            Divider()

            VStack(alignment: .leading, spacing: 8) {
                Text(String(localized: "Breakdown"))
                    .font(.headline)

                ForEach(result.rows) { row in
                    HStack(alignment: .top) {
                        Text(row.label)
                            .frame(maxWidth: .infinity, alignment: .leading)
                        VStack(alignment: .trailing, spacing: 2) {
                            Text(CurrencyFormatter.format(row.amount, currencyCode: currencyCode))
                            Text(
                                String(
                                    localized: "\(row.percentage, format: .number.precision(.fractionLength(1)))% · \(row.count) transactions"
                                )
                            )
                                .font(.caption2)
                                .foregroundStyle(Color.gray)
                        }
                    }
                    .font(.caption)
                }
            }

            Text(
                String(
                    localized: "Generated \(Date.now.formatted(date: .abbreviated, time: .shortened))"
                )
            )
            .font(.caption2)
            .foregroundStyle(Color.gray)
        }
        .foregroundStyle(Color.black)
    }

    private var subtitle: String {
        var parts: [String] = [result.grouping.displayName]
        if let type = result.transactionType {
            parts.append(type == .income ? String(localized: "Income") : String(localized: "Expenses"))
        }
        if let range = result.dateRange {
            let start = range.lowerBound.formatted(date: .abbreviated, time: .omitted)
            let end = range.upperBound.formatted(date: .abbreviated, time: .omitted)
            parts.append("\(start) – \(end)")
        }
        return parts.joined(separator: " · ")
    }
}
